apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smart-news-service
  namespace: apps
spec:
  values:
    image:
      repository: cristianrb/smartnews
      tag: latest
    encryptedSecret:
      JDBC_DATABASE_URL: AgBrQILJZTVo/oqfAbG2eP8ktnf8evz5y/A5tB8vOzsOdHQYqTNbuTZ5Kj0ppSB77CQQEtBgIvnEIpMWMgUbZjDGExA8Xm797z7bOCj55RMqQjkQskVq1rlWE0vvHe3/za2hog/2C1jC925ydAQcEZwxfgHWH7IEFOZ2Liis6R9ClQnfBmD15eEK2dXe/JA58nZyyTwaEi/ZeT+GeNuB43OaRe5VDb7Ib9h53qFZC1hhOqVpi/lplsIHuXSIIy0rBjyBLLH74RV/ROBFYdXf6Jy2llTU0VngW/MRRUu6lHxmWfm8Kc4QptLjJskekQ+lZnB3qyypIZ6u4sxPpkCXzlwvjAZWeuQ6oxy+xSsGl6qwfvQhGXrHKz615R0TJfrqkZBx56vmnpACWORKMHcbrPWB0l6W096yh22qVZ46rAwh6rKD6rnlddQHXDBtLIqLjZujF9pauPLVnarWOi2QjRxHxkF/oe6iXElvpgwnysXglzA0lmBgg/2X76k/acAGne9yzY5PyW6DohQguQ3XXbUG7ygepTcAZNS/UA9iQuKUs9aSmLOP2RnmvoRhKUHrDoXL09pVjEFgROVkdRqOUdF3h2GIXvm75B49sFSlZA4WesUfsK9r+p91Eu+CS0T7/6dw9iv/nlGSXF3hhsXSPcSCeVkovHdgaoTSyHz+79ceuD8DtUsw4ywNum2pt+KOR52phH2yeS9uRWiW4AzVnlWwNwwIr/Efsx0KlNmI9EOOz0cWFmyRLbtenHyV6E9x0XYP6aSkzBj7cClUkDb/3M4DBkrJ
