{{- if .Values.encryptedSecret -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "secret" . }}
      namespace: {{ .Release.Namespace }}
  encryptedData:
    {{- toYaml .Values.encryptedSecret | nindent 4 }}
{{- end -}}