apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: smart-news-service
  namespace: flux-system
spec:
  image: cristianrb/smartnews
  interval: 1m0s
  exclusionList:
    - ^latest$
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: smart-news-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: smart-news-service
  filterTags:
    pattern: '^[0-9]{14}$'
  policy:
    alphabetical:
      order: desc
