---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYOXdtvUyZZR1dO267zy7S4hobB0omtd4V4yRtb/udCG50+37pmLDuNIbibP2DSppoNRR5RuOFhqOEFJ4kYWu2d1BSQTMBLpLmO/8q5ANejWPltLm1GnQFa52hVYIOnpfHNRm/lRXkx7E+zq6b5wrXfHSWSdEey8b0shRl0iGapUspgP5ADQxC+g2b/xJ5UgjYnGvVhcX5tgNFW6ekjDgV3wyCq8M9OG25HwlMUyDIx0NfFs0E3yyNvKoKO+sVVlgrMXzNZ3iRX4AeMtIz3XMr0Wx//1be7vBneD56+0EWuySSB60Qi8r/T+t73l/ybW6rZFTCH+0hqgRymLCIZKEMnZODJVdcqGaZ/DpdRR0NdsrOaX2VX1XAyymX+IBMRBSEYU/plUrms1K+gsIJo2B45V5oORS1YtbSGfKUtuXYJDelCvqV6pZ2/arT7fdRHzOxs2Z7HnfdbZ7x7NNJr/GiOwxhWqMHN1GtnxHmL8CNEOkLY+G57n7C8k4IGaVNyM1JzcYPVPKpkSM8mMlv8CbzRMKNF93vdBc/ynHdD0s6tERQ1BcS4d/AQ6D+Czyy1AWEn6ChdeJkpHhKFOJHA4U1Me5Kgcls6Z/4OlpET8MSrO5DGaVdRb/oSVzkqXa0aoIIAQp+Pm1AYXFgv3ToDf+lGPKXTHcaJLXinx4MNfN6BrI4q1xkjt+E+H8gPeNMcwHs6i4D1DpkJy2Loruo7mbzYbMa4lao/cwGoM/ygUbk6j4bQ49u7Wbv
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
