---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: apps
spec:
  encryptedData:
    api-token: AgAfXm0SXBhMo9gf8DwRHgf+44EF1m4Mw+9RvK6i03MM+Renwj9MnU8LfW9mSuKeU+DLix2X6+oXi1+xTCNSL0Xv1fvYUb5EsXiRhlYb3S5i4cqjpZInq+2brqD+HYiogOjZzpmm6KcgikAfgNTYqqu/rllI2xXneaGf2O/yuWomOEKdV98kSubQzSy9OKQSYDAaCAcMieq1XDa6/HT1VlxyOeCLwAXE2CLUOMHgsQBA94CJU1Xead8a3bz+t6eInsSWt+G+/mSriPCTejx3rkHvltD+oqf3m3vJU+xzaQhsZzb5KT0Y8b+fnxZEhk3zroem65LkIyXO1zK6kZ+n8f6dseOsFUo6BLcaPXwhi3T7PwSGvG7Cvb3Y+dxg46BWkbKImkE3bYOFuN+evPdKs09lpwZZxo0PKDxU582U6kJiU1qKmU2b5PmNuxIB2FaXfIj8+VDLDCI+zcxNSr7xvBa1B9FomjLd4c6nBF9rOV+aep2im8hgQxiYvdLya4o/RK+AYfO0RLXRFBRh7hBt5d6MDVAvsu/ueZ7qy9mvv17KhREiBREdKagotZITmXzZ0KNPblaEN8cicwprLYZtZ9Z2NPByG7J0DfbQBzrB/jlOAr75asuUyMPJajE6sdcIGdKLUtxiOglbzkivV4VtPGP8t7nnuwy4zQ/25WwNRfnHLXFSGxO13ADKFjEhrEJ2StKI+GW7eTZ8TX6FQuoViYiEFsWLYRYATcVXGB2KIskuM5V//Y51F5SA
  template:
    metadata:
      name: cloudflare-api-token
      namespace: apps
