---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: flux-system
spec:
  encryptedData:
    api-token: AgAeXDA5sfoPtorRm0OIESW7AlBuOFCD/yMK0iaRHbHs1teJnpR7MRJE3QxTeUsWFga9Lu1TGpKgGfizuI7rPe1iKT7bDGfAmTZ9QAESSRMOGhPix6ecHTiGaaisTIdve+atU1iuYD/SoInKb9P71LjlzTLhl2AajYJtCShSI0/NMI64SSK3tlDPrT0TbTk5+03DsGFOuoiydTtY9yKhTGdwubuxQiwMG3xC/N8/ofJQjWBbvb7GUUqbC6Fj3SbX8WzK/jc+iKaLOYQuj0wIsF/dsAOub4pbBVwcBTpYJWvGZrtYhXBjTG+cXSTFPkVDSX77QX55QuspQmEjRCfEZYyqc8lRNiQL9cFbT8/qqMTnyCWbZaXQlsBeseTkvgAYHDr4IJiJke2uxqW8O7Nf0C+vIXaxFH3gaPm2DHE8HaqWBiEOBDbIWdszAMmn2hK8tQJSWH66NcfUOiyoaL+P1IqDpmIwmwZm3v7iopZLXBC1ZFkfOUiPNY/P/zmbNUOu+yPfzFdr4cXxBOaVaveuibBedaaxhsoHw8P1DrE28h5Tl3y7XnN/Qk95Y1utt9fQS+CQZoArOPI0mXvLiV82CiKFNeqOVY4tYyS6NPQ5PTfJbsN6IuRhMPeS+3WB9AcLmnJlHBTof7xCl8VW1SkotPaSk+gVTtoyZhdy/vviUIMfbisjbFbnSo4Qhqt7koTdKQLfXo64Z7L8301mP5netNtZw7xWT5pimR01PL4FSm/q9YXXVzl5ly9T
  template:
    metadata:
      name: cloudflare-api-token
      namespace: flux-system
