apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
      kind: HelmRelease
      namespace: flux-system
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@cristianruiz.dev
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: traefik
