apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smart-news-service
  namespace: apps
spec:
  releaseName: smart-news-service
  interval: 5m
  chart:
    spec:
      chart: ./flux/charts/service-chart
      version: ">0.0.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
