---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  dependsOn:
    - name: cert-manager
      kind: HelmRepository
      namespace: flux-system
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.19.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
